spring:
  application:
    name: resto
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://188.225.36.113:3306/resto?useUnicode=true&serverTimezone=Asia/Almaty&characterEncoding=UTF-8
    username: onion
    password: OnionBot2020@
    hikari:
      auto-commit: false
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    database: mysql
    show-sql: false
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.generate_statistics: false
      hibernate.jdbc.lob.non_contextual_creation: true
    hibernate:
      ddl-auto: update
      cache:
        #required - turn on L2 cache.
        use_second_level_cache: true
        #optional - turn on query cache.
        use_query_cache: true
        region:
          #required - classpath to cache region factory.
          factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
  liquibase:
    enabled: false







